### ISSUE TITLE
Analysis: KOSTVAL Integration into DPS

### ISSUE THREAD

**Issue by aseles13** [artefactual-sdps/enduro#1073] opened 2024-11-15 13:43 UTC
**Describe the issue:**
SFA has a of steps that take place in a step called 'Pre-ingest' one step in that process is file format validation using a bundled tool application called KOST-Val, which includes tools like JHOVE, FFMPeg, jplyzer, BadPeggy, pngcheck, mkvalidator, XML LINT (for character encoding etc), and a custom script for checking SIARD files.

During the September 2023 onsite meetings we agreed to integrate file format validation into ingest, however we needed to evaluate how we would integrate different tools and which tools could/should be integrated.

We had a follow up meeting on this topic on [29 October 2024](https://docs.google.com/document/d/1Az1q1tcFVfQp3YhQbMSNvJDu-wwJyJeKZEu2BqHBXTc/edit?tab=t.0)

**Outcome:** 
Based on the October 29 meeting we want to re-examine and analyze the integration of KOST-Val tools to be able to guide upcoming work for the 29 November Sprint.

**Comment by sallain** [comment] 2024-11-18 18:59
Duplicate of https://github.com/artefactual-sdps/preprocessing-sfa/issues/63

**Closed as completed by sallain** 2024-11-18 18:59 UTC
Labels: client: SFA
