### ISSUE TITLE
Feature: Accept bucket addresses in config, e.g. "s3://..."

### ISSUE THREAD

**Issue by Diogenesoftoronto** [artefactual-sdps/enduro#549] opened 2023-06-17 03:18 UTC
Single config argument to define buckets, very flexible since users can choose mem-based or file-based schemes, particularly useful in integration.

**Comment by djjuhasz** [comment] 2023-06-27 01:03
Duplicate of #510.

**Closed as not planned by djjuhasz** 2023-06-27 01:03 UTC
